services:
  - type: web
    name: skin-cancer-detection
    runtime: docker
    repo: https://github.com/akshajp77/skin-cancer-detection
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /health
